<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Admin\Category;
use Illuminate\Support\Carbon;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Category::insert([
            [
                'id' => 1,
                'name' => 'Food Supplements',
                'slug' => 'food-supplements-69ff291e45cb7',
                'title' => '50% Off On Food Supplements Brands',
                'description' => 'Find the latest Food Supplements coupon codes, promo offers, and discount deals to save on everyday nutrition and wellness products. This category includes vitamins, protein powders, minerals, herbal supplements, weight management products, and daily health boosters from trusted brands. Whether you want to improve fitness, support immunity, or maintain a healthy lifestyle, explore verified deals that help you choose the right supplements at better prices while saving more on your regular health needs',
                'image' => '1778950964_vitamins.png',
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 0,
                'created_at' => '2026-05-09 16:31:26',
                'updated_at' => '2026-05-30 18:55:14',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'id' => 2,
                'name' => 'Food & Restaurants',
                'slug' => 'food-restaurants-69ff2915c9974',
                'title' => '50% Off On Food & Restaurants Stores',
                'description' => 'Find the latest Food & Restaurants coupon codes, promo offers, and discount deals to save on your favorite meals and dining experiences. This category includes restaurant discounts, fast food deals, online food delivery offers, takeout savings, cafe promotions, and special dining vouchers from popular food brands. Whether you\'re ordering at home or dining out, explore verified deals that help you enjoy tasty meals at better prices while saving more every time you eat out',
                'image' => '1778951507_burger.png',
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 0,
                'created_at' => '2026-05-09 16:31:17',
                'updated_at' => '2026-05-30 18:56:06',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'id' => 3,
                'name' => 'Eyewear',
                'slug' => 'eyewear-69ff290c49fe1',
                'title' => 'Best Eyewear Promo Codes & Discounts',
                'description' => 'Save even more on trendy eyewear with the newest coupon codes and discounts. Get discounts on prescription glasses, sunglasses, blue-light glasses, contact lenses, and fashionable eyewear from trusted brands.',
                'image' => '1779743171_sunglasses.png',
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 1,
                'created_at' => '2026-05-09 16:31:08',
                'updated_at' => '2026-05-26 01:27:50',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'id' => 4,
                'name' => 'Erotic',
                'slug' => 'erotic-69ff2900e24bd',
                'title' => '50% Off On Erotic Brands',
                'description' => 'Find best Coupon Codes and Offers on Erotic Category sections get special products and discounts.',
                'image' => '1778952430_eighteen.png',
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 0,
                'created_at' => '2026-05-09 16:30:56',
                'updated_at' => '2026-05-30 19:01:16',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'id' => 5,
                'name' => 'Entertainment',
                'slug' => 'entertainment-69ff28f4c75d5',
                'title' => '50% Off ON Entertainment Brands',
                'description' => 'Find the latest Entertainment Coupon Codes, Promo Offers, and discount deals to save on movies, streaming services, events, and fun experiences.',
                'image' => null,
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 0,
                'created_at' => '2026-05-09 16:30:44',
                'updated_at' => '2026-05-30 19:03:55',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'id' => 6,
                'name' => 'Electronics',
                'slug' => 'electronics-69ff28b7db043',
                'title' => '50% Off On Electronics Stores',
                'description' => 'Find the latest Electronics coupon codes, promo offers, and discount deals from top brands. This category includes smartphones, laptops, TVs, headphones, cameras, smartwatches, and home appliances. Whether you’re upgrading your tech, buying gadgets for daily use, or shopping for home electronics, explore verified deals that help you save money while choosing reliable and high-quality products.',
                'image' => null,
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 0,
                'created_at' => '2026-05-09 16:29:43',
                'updated_at' => '2026-05-30 19:06:47',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'id' => 7,
                'name' => 'Education',
                'slug' => 'education-69ff28ae389f6',
                'title' => '50% Off On Education Brands',
                'description' => 'Find the latest Education coupon codes, promo offers, and discount deals on learning platforms and academic tools. This category includes online courses, e-learning subscriptions, certification programs, tutoring services, study materials, and educational apps from trusted providers. Whether you are a student, professional, or lifelong learner, explore verified deals that help you learn new skills and grow your knowledge while saving more on quality education resources.',
                'image' => null,
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 0,
                'created_at' => '2026-05-09 16:29:34',
                'updated_at' => '2026-05-30 19:08:20',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'id' => 8,
                'name' => 'Departmental Stores',
                'slug' => 'departmental-stores-69ff28a3b9ef0',
                'title' => '50% Off On Departmental Stores',
                'description' => 'Find the latest Departmental Stores Coupon Codes, Cromo Offers, and discount deals to save on everyday shopping needs. This category includes groceries, clothing, home essentials, personal care products, electronics, and household items from popular departmental stores.',
                'image' => null,
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 0,
                'created_at' => '2026-05-09 16:29:23',
                'updated_at' => '2026-05-30 19:10:14',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'id' => 9,
                'name' => 'Apparel',
                'slug' => 'apparel-69ff2637ca3c1',
                'title' => '50% Off On Apparel Brands',
                'description' => 'Find the latest Apparel Coupon Codes, Promo Offers, and Discount Deals on stylish clothing for men, women, and kids.',
                'image' => null,
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 1,
                'created_at' => '2026-05-09 16:19:03',
                'updated_at' => '2026-05-30 19:38:56',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'id' => 10,
                'name' => 'Art & Craft',
                'slug' => 'art-craft-69ff270fe8fee',
                'title' => '50% Off ON Art & Craft Stores',
                'description' => 'Discover the latest Art & Craft Coupon Codes, Promo Offers, and Discount Deals on creative supplies and DIY essentials.',
                'image' => null,
                'parent_id' => null,
                'status' => 'enable',
                'is_sensitive' => 0,
                'hidden_user_ids' => null,
                'mark_home' => 0,
                'created_at' => '2026-05-09 16:22:39',
                'updated_at' => '2026-05-30 19:37:10',
                'created_by' => null,
                'updated_by' => null,
            ],

        ]);
    }
}
