<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            
            [
                'id' => 1,
                'user_id' => 1,
                'store_id' => 1,
                'event_id' => null,
                'category_id' => null,
                'product_name' => 'ADIZERO EVO SL EXO Shoes',
                'product_title' => 'ADIZERO EVO SL EXO Shoes',
                'old_price' => '$190',
                'current_price' => '$150',
                'detail' => 'Step into speed with the ADIZERO EVO SL EXO Shoes from Adidas. Designed for lightweight comfort and responsive performance, these running shoes deliver excellent cushioning and support to help you move confidently during training, workouts, or everyday wear.',
                'image' => '1780479418.jpg',
                'url' => 'https://www.adidas.com/us/adizero-evo-sl-shoes/JH6206.html',
                'created_at' => '2026-06-03 13:36:58',
                'updated_at' => '2026-06-03 13:36:58',
                'slug' => 'adizero-evo-sl-exo-shoes',
                'currency_code' => '',
                'currency_symbol' => '',
            ],
            [
                'id' => 2,
                'user_id' => 1,
                'store_id' => 2,
                'event_id' => null,
                'category_id' => null,
                'product_name' => 'Longevity Creatine NAD Unflavored',
                'product_title' => 'Longevity Creatine NAD Unflavored',
                'old_price' => '$40.99',
                'current_price' => '$32.99',
                'detail' => 'Support healthy aging, strength, and cognitive wellness with an advanced formula featuring 5g of creatine and NAD+ to help boost NAD+ levels. Designed to support daily performance, energy, and overall well-being.',
                'image' => '1780475639.jpg',
                'url' => 'https://www.gnc.com/creatine-shopall/448041.html',
                'created_at' => '2026-06-03 12:33:59',
                'updated_at' => '2026-06-03 12:33:59',
                'slug' => 'longevity-creatine-nad-unflavored',
                'currency_code' => '',
                'currency_symbol' => '',
            ],
            [
                'id' => 3,
                'user_id' => 1,
                'store_id' => 3,
                'event_id' => null,
                'category_id' => null,
                'product_name' => 'Protein Bar - Orange Creamsicle',
                'product_title' => 'Protein Bar - Orange Creamsicle',
                'old_price' => '$35.99',
                'current_price' => '$30.99',
                'detail' => 'Enjoy the delicious taste of the Barebells Orange Creamsicle Protein Bar, packed with 20g of protein and no added sugar. A convenient and satisfying snack that helps support your active lifestyle while delivering great flavor in every bite.',
                'image' => '1780475926.jpg',
                'url' => 'https://www.gnc.com/protein-bars/575069.html',
                'created_at' => '2026-06-03 12:38:46',
                'updated_at' => '2026-06-03 12:38:46',
                'slug' => 'protein-bar-orange-creamsicle',
                'currency_code' => '',
                'currency_symbol' => '',
            ],
            [
                'id' => 4,
                'user_id' => 1,
                'store_id' => 4,
                'event_id' => null,
                'category_id' => null,
                'product_name' => 'Hydration Sticks Strawbango',
                'product_title' => 'Hydration Sticks Strawbango',
                'old_price' => '$39.99',
                'current_price' => '$29.99',
                'detail' => 'Stay refreshed with Hydration Sticks Strawbango and enjoy a delicious blend of strawberry and mango flavor in every sip. Designed for convenient daily hydration, these easy-to-use sticks help you stay energized and refreshed whether you\'re at home, at work, or on the go.',
                'image' => '1780475368.jpg',
                'url' => 'https://www.gnc.com/hydration-drinks/528176.html',
                'created_at' => '2026-06-03 12:29:28',
                'updated_at' => '2026-06-03 12:29:28',
                'slug' => 'hydration-sticks-strawbango-1',
                'currency_code' => '',
                'currency_symbol' => '',
            ],
            [
                'id' => 5,
                'user_id' => 1,
                'store_id' => 5,
                'event_id' => null,
                'category_id' => null,
                'product_name' => 'Lip Toy pH',
                'product_title' => 'Lip Toy pH Staining Lip Oil',
                'old_price' => '$30',
                'current_price' => '$24',
                'detail' => null,
                'image' => '1780248912.jpg',
                'url' => 'https://www.urbandecay.com/lips/lip-toy-ph-staining-lip-oil/ud1313.html',
                'created_at' => '2026-05-31 21:35:12',
                'updated_at' => '2026-05-31 21:35:12',
                'slug' => 'lip-toy-ph-1',
                'currency_code' => '',
                'currency_symbol' => '',
            ],
            [
                'id' => 6,
                'user_id' => 1,
                'store_id' => 6,
                'event_id' => null,
                'category_id' => null,
                'product_name' => 'Glow Waterproof Setting',
                'product_title' => 'Glow Waterproof Setting',
                'old_price' => '$44',
                'current_price' => '$34',
                'detail' => null,
                'image' => '1780249060.jpg',
                'url' => 'https://www.urbandecay.com/all-nighter-glow-waterproof-setting-spray/ud1302.html?dwvar_ud1302_size=FullSize',
                'created_at' => '2026-05-31 21:37:40',
                'updated_at' => '2026-05-31 21:37:40',
                'slug' => 'glow-waterproof-setting',
                'currency_code' => '',
                'currency_symbol' => '',
            ],
            [
                'id' => 7,
                'user_id' => 6,
                'store_id' => 7,
                'event_id' => null,
                'category_id' => null,
                'product_name' => 'GEL-Nimbus® 28',
                'product_title' => 'GEL-Nimbus® 28',
                'old_price' => null,
                'current_price' => '$169.95',
                'detail' => 'Experience premium comfort with the GEL-Nimbus® 28. Designed with soft cushioning, smooth support, and responsive performance, these running shoes are ideal for daily runs, long distances, and all-day comfort.',
                'image' => '1781307145.jpg',
                'url' => 'https://www.zappos.com/p/womens-asics-gel-nimbus-28-cloud-grey-dusty-mauve/product/10046853/color/1130207',
                'created_at' => '2026-06-13 03:32:25',
                'updated_at' => '2026-06-13 03:32:25',
                'slug' => 'gel-nimbus-28',
                'currency_code' => '',
                'currency_symbol' => '',
            ],
            [
                'id' => 8,
                'user_id' => 1,
                'store_id' => 8,
                'event_id' => null,
                'category_id' => null,
                'product_name' => 'WHEY Protein Cinnabon',
                'product_title' => 'WHEY Protein Cinnabon',
                'old_price' => '$64.99',
                'current_price' => '$54.99',
                'detail' => 'Fuel your fitness goals with WHEY Protein – Cinnabon® (27 Servings). Enjoy delicious cinnamon roll flavor and quality protein support in every serving.',
                'image' => '1780475048.jpg',
                'url' => 'https://www.gnc.com/whey-protein/528048.html',
                'created_at' => '2026-06-03 12:24:08',
                'updated_at' => '2026-06-03 12:24:08',
                'slug' => 'whey-protein-cinnabon',
                'currency_code' => '',
                'currency_symbol' => '',
            ],

            [
                'id' => 9,
                'user_id' => 1,
                'store_id' => 9,
                'event_id' => 3,
                'category_id' => null,
                'product_name' => 'Nike Air Max Hoodie',
                'product_title' => 'Premium Winter Hoodie for Men & Women',
                'old_price' => '$120',
                'current_price' => '$79',
                'detail' => 'Comfortable premium fleece hoodie with modern fit, soft fabric, and winter collection design. Perfect for casual wear and daily styling.',
                'image' => '1779747556.png',
                'url' => 'https://example.com/nike-air-max-hoodie',
                'created_at' => '2026-05-26 02:19:16',
                'updated_at' => '2026-05-26 02:19:16',
                'slug' => 'nike-air-max-hoodie',
                'currency_code' => '',
                'currency_symbol' => '',
            ],

            [
                'id' => 10,
                'user_id' => 1,
                'store_id' => 1,
                'event_id' => null,
                'category_id' => null,
                'product_name' => 'Jelly Much Eyeshadow Stick',
                'product_title' => 'Jelly Much Eyeshadow Stick',
                'old_price' => null,
                'current_price' => '10$',
                'detail' => 'Add instant sparkle with the Jelly Much Eyeshadow Stick. Featuring a unique jelly texture and a cooling water-based formula, it delivers a shimmering wet-look finish with effortless, buildable color for any occasion.',
                'image' => '1780746592.jpg',
                'url' => 'https://colourpop.com/products/happy-tears-jelly-much-eyeshadow-stick',
                'created_at' => '2026-06-06 15:49:52',
                'updated_at' => '2026-06-06 15:49:52',
                'slug' => 'jelly-much-eyeshadow-stick',
                'currency_code' => '',
                'currency_symbol' => '',
            ],
        ]);
    }
}
